# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.9.4

pipelines:
  default:
    - parallel:
      - step:
          name: 'Django Universities API test'
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - export PYTHONPATH=$PYTHONPATH:$PYTHONPATH/api/pestcontrol
            - pytest api/pestcontrol -s -v --durations=0

