# Generated by Django 3.2.3 on 2021-05-27 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Hiring', 'Hiring'), ('Hiring Freeze', 'Freeze'), ('Layoffs', 'Layoffs')], default='Hiring', max_length=50)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2021, 5, 27, 14, 17, 29, 397947))),
                ('application_link', models.URLField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
